export const getFileIcon = (fileName: string): string => {
  const extension = fileName.split('.').pop()?.toLowerCase() || ''

  const iconMap: Record<string, string> = {
    pdf: '📄',
    doc: '📝',
    docx: '📝',
    xls: '📊',
    xlsx: '📊',
    ppt: '🎯',
    pptx: '🎯',
    txt: '📄',
    csv: '📊',
    json: '⚙️',
    xml: '⚙️',
    jpg: '🖼️',
    jpeg: '🖼️',
    png: '🖼️',
    gif: '🖼️',
    svg: '🖼️',
    webp: '🖼️',
    mp3: '🎵',
    mp4: '🎬',
    avi: '🎬',
    mov: '🎬',
    mkv: '🎬',
    zip: '📦',
    rar: '📦',
    '7z': '📦',
    tar: '📦',
    gz: '📦',
    exe: '⚙️',
    dmg: '⚙️',
    apk: '⚙️',
    html: '🌐',
    css: '🎨',
    js: '⚙️',
    ts: '⚙️',
    jsx: '⚙️',
    tsx: '⚙️',
    py: '🐍',
    java: '☕',
    cpp: '⚙️',
    c: '⚙️',
    sh: '⚙️',
    bash: '⚙️',
    sql: '🗄️',
    md: '📝',
  }

  return iconMap[extension] || '📁'
}
